import { ASANA_SWIMLANE_TYPE } from './types'

export const AsanaSwimlaneTypes = [
  ASANA_SWIMLANE_TYPE.TODO,
  ASANA_SWIMLANE_TYPE.IN_PROGRESS,
  ASANA_SWIMLANE_TYPE.REVIEW,
  ASANA_SWIMLANE_TYPE.DONE,
]
