import { ASANA_SWIMLANE_KIND } from './types'

export const AsanaSwimlaneTypes = [
  ASANA_SWIMLANE_KIND.TODO,
  ASANA_SWIMLANE_KIND.IN_PROGRESS,
  ASANA_SWIMLANE_KIND.REVIEW,
  ASANA_SWIMLANE_KIND.DONE,
]
